name: Github Actions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5
    - uses: treeform/setup-nim-action@v6

    - run: nimby sync -g nimby.lock

    # Build the examples
    - run: nim c examples/basicwindow/basicwindow.nim
    - run: nim c examples/calculator/calculator.nim
    - run: nim c examples/gameplayer/gameplayer.nim
    - run: nim c examples/menu/menu.nim
    - run: nim c examples/panels/panels.nim
    - run: nim c examples/the7gui/the7gui.nim

    # Run example tests
    - name: Run calculator tests
      working-directory: examples/calculator
      run: nim r tests/test.nim

    - name: Run basicwindow tests
      working-directory: examples/basicwindow
      run: nim r tests/test.nim